[
    {
        "content": "<p>I've been noticing that it basically always seems nicer to use <code>Task.onErr</code> to handle errors than <code>Task.attempt</code> - any reason we should keep both, given you can always build your own <code>Task.attempt</code>in userspace with <code>|&gt; Task.map Ok |&gt; Task.onErr Err |&gt; Task.await</code>?</p>",
        "id": 410897463,
        "sender_full_name": "Richard Feldman",
        "timestamp": 1704225218
    },
    {
        "content": "<p>I think having both await and attempt is a bit confusing so Iâ€™m in favor of removing attempt</p>",
        "id": 410898638,
        "sender_full_name": "Isaac Van Doren",
        "timestamp": 1704225773
    },
    {
        "content": "<p>I find I prefer Task.attempt sometimes, I use it frequently. On my mobile rn but I can dig out some examples of where I like to use it.</p>",
        "id": 410902870,
        "sender_full_name": "Luke Boswell",
        "timestamp": 1704228014
    },
    {
        "content": "<p>The examples repo has <a href=\"https://github.com/search?q=repo%3Aroc-lang%2Fexamples%20attempt&amp;type=code\">three examples</a> that use attempt. Rewriting those to use onErr and seeing how that looks seems like a good idea. <code>onErr</code> seems much easier to understand and remember so it would be nice to cut <code>attempt</code>.</p>",
        "id": 410977643,
        "sender_full_name": "Anton",
        "timestamp": 1704271963
    },
    {
        "content": "<p>Attempt enables you to use a task as a result. I think it is better unless you strictly are able to merge and pipeline all errors (or if you just need a result for something). So I find it useful.</p>",
        "id": 411036485,
        "sender_full_name": "Brendan Hansknecht",
        "timestamp": 1704297092
    }
]